export const wordCategories: Record<string, string[]> = {
  Fútbol: [
    "Messi",
    "Cristiano Ronaldo",
    "Balón de oro",
    "Penalti",
    "Tarjeta roja",
    "Portero",
    "Córner",
    "Fuera de juego",
    "Champions League",
    "Mundial",
    "VAR",
    "Gol de chilena",
    "Tiro libre",
    "Banquillo",
    "Árbitro",
  ],
  Comida: [
    "Pizza",
    "Sushi",
    "Tacos",
    "Paella",
    "Hamburguesa",
    "Pasta carbonara",
    "Ceviche",
    "Empanadas",
    "Ramen",
    "Croissant",
    "Guacamole",
    "Tortilla española",
    "Kebab",
    "Pad Thai",
    "Lasaña",
  ],
  Animales: [
    "Elefante",
    "Tiburón",
    "Águila",
    "Canguro",
    "Pulpo",
    "Koala",
    "Pingüino",
    "Camaleón",
    "Delfín",
    "Oso polar",
    "Flamenco",
    "Gorila",
    "Medusa",
    "Tucán",
    "Armadillo",
  ],
  Películas: [
    "Titanic",
    "Avatar",
    "El Padrino",
    "Matrix",
    "Jurassic Park",
    "Star Wars",
    "El Rey León",
    "Inception",
    "Forrest Gump",
    "Gladiator",
    "Interstellar",
    "Toy Story",
    "Shrek",
    "Harry Potter",
    "Batman",
  ],
  Música: [
    "Guitarra eléctrica",
    "DJ",
    "Concierto",
    "Reggaeton",
    "Rock and Roll",
    "Piano",
    "Festival",
    "Micrófono",
    "Batería",
    "Karaoke",
    "Autotune",
    "Vinilo",
    "Spotify",
    "Banda de garage",
    "Eurovision",
  ],
  Videojuegos: [
    "Mario Bros",
    "Minecraft",
    "Fortnite",
    "Among Us",
    "FIFA",
    "Pokemon",
    "GTA",
    "Call of Duty",
    "Zelda",
    "Tetris",
    "Pac-Man",
    "League of Legends",
    "Sonic",
    "Roblox",
    "Crash Bandicoot",
  ],
  Lugares: [
    "Torre Eiffel",
    "Machu Picchu",
    "Gran Muralla China",
    "Coliseo Romano",
    "Pirámides de Egipto",
    "Estatua de la Libertad",
    "Taj Mahal",
    "Big Ben",
    "Cristo Redentor",
    "Santorini",
    "Las Vegas",
    "Disney World",
    "Safari africano",
    "Playa del Caribe",
    "Montaña Everest",
  ],
  Profesiones: [
    "Astronauta",
    "Chef",
    "Bombero",
    "Médico",
    "Piloto",
    "Influencer",
    "Detective",
    "Mago",
    "Youtuber",
    "Veterinario",
    "Arqueólogo",
    "DJ",
    "Fotógrafo",
    "Streamer",
    "Entrenador personal",
  ],
}

export function getRandomWord(category: string): string {
  const words = wordCategories[category]
  if (!words) return "Palabra"
  return words[Math.floor(Math.random() * words.length)]
}

export function getCategories(): string[] {
  return Object.keys(wordCategories)
}
