export const wordCategories: Record<string, string[]> = {
  Fútbol: [
    "Messi",
    "Cristiano Ronaldo",
    "Neymar",
    "Kylian Mbappé",
    "Erling Haaland",
    "Robert Lewandowski",
    "Karim Benzema",
    "Kevin De Bruyne",
    "Luka Modrić",
    "Sergio Ramos",
    "Virgil van Dijk",
    "Harry Kane",
    "Mohamed Salah",
    "Sadio Mané",
    "Eden Hazard",
    "Antoine Griezmann",
    "Paulo Dybala",
    "Luis Suárez",
    "Zlatan Ibrahimović",
    "Xavi Hernández",
    "Andrés Iniesta",
    "Gerard Piqué",
    "Sergio Busquets",
    "Jordi Alba",
    "Marc-André ter Stegen",
    "Alisson Becker",
    "Thibaut Courtois",
    "Jan Oblak",
    "Manuel Neuer",
    "Gianluigi Buffon",
    "Andrea Pirlo",
    "Francesco Totti",
    "Ronaldinho",
    "Rivaldo",
    "Ronaldo Nazário",
    "Zinedine Zidane",
    "David Beckham",
    "Wayne Rooney",
    "Steven Gerrard",
    "Frank Lampard",
    "Didier Drogba",
    "Samuel Eto'o",
    "Clarence Seedorf",
    "Kaká",
    "Philipp Lahm",
    "Bastian Schweinsteiger",
    "Thomas Müller",
    "Arjen Robben",
    "Franck Ribéry",
    "Ryan Giggs",
    "Paul Scholes",
    "Nemanja Vidić",
    "Rio Ferdinand",
    "Fernando Torres",
    "Andriy Shevchenko",
    "Roberto Carlos",
    "Cafú",
    "Dani Alves",
    "Marcelo",
    "Diego Maradona",
    "Pelé",
    "Johan Cruyff",
    "George Best",
    "Eric Cantona",
    "Patrick Vieira",
    "Claude Makélélé",
    "Yaya Touré",
    "Didier Deschamps",
    "Paolo Maldini",
    "Alessandro Nesta",
    "Fabio Cannavaro",
    "Gennaro Gattuso",
    "Ruud van Nistelrooy",
    "Robin van Persie",
    "Carlos Tévez",
    "Ángel Di María",
    "Gonzalo Higuaín",
    "Arturo Vidal",
    "Alexis Sánchez",
    "James Rodríguez",
    "Radamel Falcao",
    "Chicharito Hernández",
    "Rafa Márquez",
    "Hugo Sánchez",
    "Anderson Talisca",
    "Son Heung-min",
    "João Félix",
    "Bruno Fernandes",
    "Bernardo Silva",
    "Riyad Mahrez",
    "Marco Reus",
    "Jadon Sancho",
    "Trent Alexander-Arnold",
    "Andrew Robertson",
    "Ngolo Kanté",
    "Joško Gvardiol",
    "Pedri",
    "Gavi",
    "Jude Bellingham",
    "Vinícius Júnior",
    "Rodrygo Goes",
    "Federico Valverde",
  ],
  Comida: [
    "Pizza",
    "Sushi",
    "Tacos al pastor",
    "Tacos de carne asada",
    "Tacos de barbacoa",
    "Paella",
    "Hamburguesa",
    "Pasta carbonara",
    "Ceviche",
    "Empanadas",
    "Ramen",
    "Croissant",
    "Guacamole",
    "Tortilla española",
    "Kebab",
    "Pad Thai",
    "Lasaña",
    "Enchiladas",
    "Chilaquiles",
    "Pozole",
    "Tamal",
    "Arepas",
    "Pupusas",
    "Hot dog",
    "Nachos",
    "Burrito",
    "Fajitas",
    "Quesadilla",
    "Sopa de tortilla",
    "Sopa de tomate",
    "Gazpacho",
    "Crema de champiñones",
    "Pollo asado",
    "Pollo frito",
    "Pollo teriyaki",
    "Costillas BBQ",
    "Filete de res",
    "Carne asada",
    "Salchichas",
    "Albondigas",
    "Paella de mariscos",
    "Pescado a la plancha",
    "Salmón al horno",
    "Calamares fritos",
    "Gyozas",
    "Dim sum",
    "Bao buns",
    "Falafel",
    "Hummus",
    "Tabulé",
    "Shawarma",
    "Chow mein",
    "Arroz frito",
    "Arroz con pollo",
    "Arroz a la cubana",
    "Risotto",
    "Mac and cheese",
    "Panini",
    "Sandwich de jamón",
    "Sandwich de pollo",
    "Tostadas",
    "Bruschetta",
    "Waffles",
    "Panqueques",
    "Crepas",
    "Helado de vainilla",
    "Helado de chocolate",
    "Nieve de limón",
    "Pastel de chocolate",
    "Pastel de queso",
    "Tiramisú",
    "Flan",
    "Arroz con leche",
    "Gelatina",
    "Brownie",
    "Donas",
    "Muffins",
    "Churros",
    "Buñuelos",
    "Galletas de chocolate",
    "Macarons",
    "Trufas de chocolate",
    "Yogur con fruta",
    "Ensalada César",
    "Ensalada griega",
    "Ensalada de frutas",
    "Smoothie de fresa",
    "Smoothie de mango",
    "Jugo de naranja",
    "Limonada",
    "Agua de horchata",
    "Agua de jamaica",
    "Café espresso",
    "Café latte",
    "Capuchino",
    "Té verde",
    "Té chai",
    "Chocolate caliente",
    "Malteada de vainilla",
    "Malteada de fresa",
  ],
  Animales: [
    "Elefante",
    "Tiburón",
    "Águila",
    "Canguro",
    "Pulpo",
    "Koala",
    "Pingüino",
    "Camaleón",
    "Delfín",
    "Oso polar",
    "Flamenco",
    "Gorila",
    "Medusa",
    "Tucán",
    "Armadillo",
    "León",
    "Tigre",
    "Pantera",
    "Jaguar",
    "Leopardo",
    "Chita",
    "Lobo",
    "Zorro",
    "Oso pardo",
    "Panda gigante",
    "Hipopótamo",
    "Rinoceronte",
    "Cebra",
    "Jirafa",
    "Búfalo",
    "Antílope",
    "Ciervo",
    "Alce",
    "Reno",
    "Mapache",
    "Castor",
    "Nutria",
    "Erizo",
    "Liebre",
    "Conejo",
    "Ratón",
    "Murciélago",
    "Topo",
    "Suricata",
    "Foca",
    "Morsa",
    "Ballena azul",
    "Orca",
    "Manta raya",
    "Caballito de mar",
    "Piraña",
    "Salmón",
    "Trucha",
    "Carpa",
    "Loro",
    "Guacamayo",
    "Cacatúa",
    "Gallo",
    "Gallina",
    "Pato",
    "Ganso",
    "Cisne",
    "Paloma",
    "Gaviota",
    "Cuervo",
    "Lechuza",
    "Búho",
    "Halcon",
    "Camello",
    "Dromedario",
    "Llama",
    "Alpaca",
    "Burro",
    "Caballo",
    "Vaca",
    "Toro",
    "Cerdo",
    "Oveja",
    "Cabra",
    "Perro",
    "Gato",
    "Hámster",
    "Cobaya",
    "Iguana",
    "Serpiente",
    "Cobra",
    "Pitón",
    "Cocodrilo",
    "Aligátor",
    "Tortuga marina",
    "Tortuga terrestre",
    "Rana",
    "Sapo",
    "Libélula",
    "Mariposa",
    "Abeja",
    "Araña",
    "Ciempiés",
    "Escorpión",
    "Caracol",
    "Babosa",
  ],
  Películas: [
    "Titanic",
    "Avatar",
    "El Padrino",
    "Matrix",
    "Jurassic Park",
    "Star Wars",
    "El Rey León",
    "Inception",
    "Forrest Gump",
    "Gladiator",
    "Interstellar",
    "Toy Story",
    "Shrek",
    "Harry Potter y la Piedra Filosofal",
    "Batman: El Caballero de la Noche",
    "El Señor de los Anillos: La Comunidad del Anillo",
    "El Señor de los Anillos: Las Dos Torres",
    "El Señor de los Anillos: El Retorno del Rey",
    "Piratas del Caribe: La Maldición del Perla Negra",
    "Buscando a Nemo",
    "Los Increíbles",
    "Ratatouille",
    "Up",
    "Wall-E",
    "Coco",
    "Intensamente",
    "Frozen",
    "Moana",
    "Encanto",
    "Spider-Man 2",
    "Spider-Man: Un Nuevo Universo",
    "Spider-Man: Sin Camino a Casa",
    "Iron Man",
    "Avengers",
    "Avengers: Infinity War",
    "Avengers: Endgame",
    "Capitán América: El Soldado del Invierno",
    "Guardianes de la Galaxia",
    "Doctor Strange",
    "Black Panther",
    "Capitán América: Civil War",
    "Thor: Ragnarok",
    "Deadpool",
    "Logan",
    "X-Men: Días del Futuro Pasado",
    "El Origen",
    "El Lobo de Wall Street",
    "El Club de la Pelea",
    "Pulp Fiction",
    "Kill Bill",
    "Django Sin Cadenas",
    "Bastardos Sin Gloria",
    "Malditos Bastardos",
    "La Lista de Schindler",
    "Rescatando al Soldado Ryan",
    "La Vida es Bella",
    "Slumdog Millionaire",
    "La La Land",
    "Whiplash",
    "El Gran Showman",
    "Bohemian Rhapsody",
    "Rocketman",
    "Parásitos",
    "Oldboy",
    "El Viaje de Chihiro",
    "Mi Vecino Totoro",
    "El Castillo Ambulante",
    "Your Name",
    "A Silent Voice",
    "Akira",
    "Ghost in the Shell",
    "El Exorcista",
    "El Conjuro",
    "Actividad Paranormal",
    "Anabelle",
    "El Aro",
    "IT",
    "El Resplandor",
    "Halloween",
    "Viernes 13",
    "Scream",
    "Rápidos y Furiosos",
    "Rápidos y Furiosos 5",
    "Rápidos y Furiosos 7",
    "Misión Imposible: Protocolo Fantasma",
    "John Wick",
    "Mad Max: Furia en el Camino",
    "300",
    "Troya",
    "Corazón Valiente",
    "La Roca",
    "Armageddon",
    "Hombres de Negro",
    "Volver al Futuro",
    "Karate Kid",
    "Rocky",
    "Rocky Balboa",
    "Creed",
    "Joker",
    "Oppenheimer",
  ],
  Música: [
    "Guitarra eléctrica",
    "DJ",
    "Concierto",
    "Reggaeton",
    "Rock and Roll",
    "Piano",
    "Festival",
    "Micrófono",
    "Batería",
    "Karaoke",
    "Autotune",
    "Vinilo",
    "Spotify",
    "Banda de garage",
    "Eurovision",
    "Pop",
    "Rock",
    "Metal",
    "Trap",
    "Rap",
    "Hip hop",
    "Salsa",
    "Bachata",
    "Merengue",
    "Cumbia",
    "Flamenco",
    "Reggae",
    "Jazz",
    "Blues",
    "Country",
    "Ópera",
    "Música clásica",
    "Sinfónica",
    "Orquesta",
    "Corazón de voces",
    "Coro",
    "Solista",
    "Banda",
    "Dueto",
    "Trío musical",
    "Cover",
    "Remix",
    "Versión acústica",
    "Playlist",
    "Altavoces",
    "Auriculares",
    "Estudio de grabación",
    "Mezcla",
    "Masterización",
    "Productor musical",
    "Compositor",
    "Letrista",
    "Cantante",
    "Vocalista",
    "Bajista",
    "Guitarrista",
    "Baterista",
    "Tecladista",
    "Saxofonista",
    "Trompetista",
    "Violinista",
    "Director de orquesta",
    "Beat",
    "Bajo",
    "Melodía",
    "Armonía",
    "Ritmo",
    "Subwoofer",
    "Ecualizador",
    "Lista de éxitos",
    "Top 50",
    "Billboard",
    "K-Pop",
    "J-Pop",
    "Indie",
    "Funk",
    "Synthwave",
    "Lo-fi",
    "Soundtrack",
    "Banda sonora",
    "A cappella",
    "Microfonía inalámbrica",
    "Auto DJ",
    "Sesión en vivo",
    "Tour mundial",
    "Gira",
    "Backstage",
    "Camerino",
    "Fan club",
    "Merch oficial",
    "Disquera",
    "Sello independiente",
    "EP",
    "Álbum",
    "Sencillo",
    "Demo",
    "Grabación casera",
    "Sample",
    "Loop",
    "Drop",
  ],
  Videojuegos: [
    "Mario Bros",
    "Minecraft",
    "Fortnite",
    "Among Us",
    "FIFA",
    "Pokémon Rojo",
    "Pokémon GO",
    "GTA V",
    "Call of Duty",
    "The Legend of Zelda: Breath of the Wild",
    "Tetris",
    "Pac-Man",
    "League of Legends",
    "Sonic",
    "Roblox",
    "Crash Bandicoot",
    "Counter-Strike",
    "Valorant",
    "Apex Legends",
    "Overwatch",
    "Rocket League",
    "Clash Royale",
    "Clash of Clans",
    "Brawl Stars",
    "PUBG",
    "Free Fire",
    "Genshin Impact",
    "Elden Ring",
    "Dark Souls",
    "Bloodborne",
    "Hollow Knight",
    "Cuphead",
    "Super Smash Bros",
    "Animal Crossing",
    "Fall Guys",
    "Subway Surfers",
    "Temple Run",
    "Angry Birds",
    "Candy Crush",
    "Plants vs Zombies",
    "God of War",
    "The Last of Us",
    "Red Dead Redemption 2",
    "Assassin's Creed",
    "Far Cry",
    "Battlefield",
    "Metal Gear Solid",
    "Resident Evil 4",
    "Resident Evil Village",
    "Silent Hill",
    "Skyrim",
    "Oblivion",
    "World of Warcraft",
    "Diablo III",
    "StarCraft",
    "Hearthstone",
    "Destiny 2",
    "Warframe",
    "Monster Hunter World",
    "Street Fighter",
    "Tekken",
    "Mortal Kombat",
    "Just Dance",
    "Need for Speed",
    "Gran Turismo",
    "Forza Horizon",
    "F1 2024",
    "NBA 2K",
    "PES eFootball",
    "Pro Evolution Soccer",
    "Tony Hawk's Pro Skater",
    "Guitar Hero",
    "Beat Saber",
    "Portal",
    "Portal 2",
    "Half-Life",
    "Half-Life 2",
    "Left 4 Dead",
    "Left 4 Dead 2",
    "Dota 2",
    "League of Legends: Wild Rift",
    "Mobile Legends",
    "Arknights",
    "Valorant Mobile",
    "Stumble Guys",
    "Geometry Dash",
    "Raft",
    "Terraria",
    "Stardew Valley",
    "Factorio",
    "Cities: Skylines",
    "SimCity",
    "The Sims 4",
    "Uno Online",
    "Parchís Star",
    "Ludo King",
    "Agar.io",
    "Slither.io",
    "Hades",
    "Baldur's Gate 3",
  ],
  Lugares: [
    "Torre Eiffel",
    "Machu Picchu",
    "Gran Muralla China",
    "Coliseo Romano",
    "Pirámides de Egipto",
    "Estatua de la Libertad",
    "Taj Mahal",
    "Big Ben",
    "Cristo Redentor",
    "Santorini",
    "Las Vegas",
    "Disney World",
    "Safari africano",
    "Playa del Caribe",
    "Montaña Everest",
    "Times Square",
    "Central Park",
    "Puente de Brooklyn",
    "Sagrada Familia",
    "Parque Güell",
    "Alhambra de Granada",
    "Cancún",
    "Riviera Maya",
    "Tulum",
    "Chichén Itzá",
    "Teotihuacán",
    "Xochimilco",
    "Chapultepec",
    "Acapulco",
    "Los Cabos",
    "Islas Maldivas",
    "Islas Galápagos",
    "Isla de Pascua",
    "Fiordos Noruegos",
    "Monte Fuji",
    "Kyoto",
    "Tokio",
    "Seúl",
    "Bangkok",
    "Singapur",
    "Hong Kong",
    "Dubái",
    "Abu Dabi",
    "Sídney",
    "Melbourne",
    "Buenos Aires",
    "Rio de Janeiro",
    "Santiago de Chile",
    "Lima",
    "Bogotá",
    "Cartagena de Indias",
    "Quito",
    "Toronto",
    "Vancouver",
    "Montreal",
    "San Francisco",
    "Los Ángeles",
    "Miami",
    "Chicago",
    "Washington D.C.",
    "Ciudad de México",
    "Guadalajara",
    "Monterrey",
    "Medellín",
    "Bariloche",
    "Patagonia",
    "Desierto del Sahara",
    "Gran Cañón",
    "Parque Yellowstone",
    "Niágara Falls",
    "Monte Kilimanjaro",
    "Serengeti",
    "Kruger National Park",
    "Isla Bora Bora",
    "Isla Tahití",
    "Hawái",
    "Maui",
    "Isla de Cozumel",
    "Isla Holbox",
    "Isla Mujeres",
    "Playa del Carmen",
    "San Miguel de Allende",
    "Pamukkale",
    "Capadocia",
    "Petra",
    "Jerusalén",
    "Belén",
    "Florencia",
    "Venecia",
    "Milán",
    "Berlín",
    "Múnich",
    "Ámsterdam",
    "Bruselas",
    "Viena",
    "Praga",
    "Budapest",
    "Estocolmo",
    "Oslo",
    "Reikiavik",
  ],
  Profesiones: [
    "Astronauta",
    "Chef",
    "Bombero",
    "Médico",
    "Piloto",
    "Influencer",
    "Detective",
    "Mago",
    "Youtuber",
    "Veterinario",
    "Arqueólogo",
    "DJ",
    "Fotógrafo",
    "Streamer",
    "Entrenador personal",
    "Profesor",
    "Maestro de primaria",
    "Maestro de secundaria",
    "Director de escuela",
    "Enfermero",
    "Odontólogo",
    "Psicólogo",
    "Psiquiatra",
    "Abogado",
    "Juez",
    "Policía",
    "Soldado",
    "Guardia de seguridad",
    "Ingeniero civil",
    "Ingeniero mecánico",
    "Ingeniero en sistemas",
    "Ingeniero eléctrico",
    "Programador",
    "Desarrollador web",
    "Desarrollador de videojuegos",
    "Diseñador gráfico",
    "Diseñador UX",
    "Arquitecto",
    "Contador",
    "Administrador de empresas",
    "Economista",
    "Banquero",
    "Corredor de bolsa",
    "Emprendedor",
    "Empresario",
    "Community manager",
    "Marketing digital",
    "Periodista",
    "Reportero",
    "Locutor de radio",
    "Presentador de televisión",
    "Actor",
    "Actriz",
    "Cantante",
    "Músico",
    "Bailarín",
    "Modelo",
    "Escritor",
    "Poeta",
    "Editor",
    "Traductor",
    "Intérprete",
    "Guía turístico",
    "Recepcionista",
    "Mesero",
    "Bartender",
    "Barista",
    "Cajero",
    "Vendedor",
    "Agente de bienes raíces",
    "Chofer",
    "Taxista",
    "Conductor de Uber",
    "Repartidor",
    "Cartero",
    "Obrero",
    "Albañil",
    "Carpintero",
    "Plomero",
    "Electricista",
    "Jardinero",
    "Agricultor",
    "Ganadero",
    "Pescador",
    "Panadero",
    "Pastelero",
    "Carnicero",
    "Estilista",
    "Peluquero",
    "Maquillista",
    "Enfermero veterinario",
    "Fisioterapeuta",
    "Nutriólogo",
    "Entrenador deportivo",
    "Analista de datos",
    "Científico",
    "Investigador",
    "Químico",
    "Biólogo",
    "Físico",
    "Astrónomo",
  ],
}

export function getRandomWord(category: string): string {
  const words = wordCategories[category]
  if (!words) return "Palabra"
  return words[Math.floor(Math.random() * words.length)]
}

export function getCategories(): string[] {
  return Object.keys(wordCategories)
}
